language: python
sudo: required

services:
  - docker

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

env:
  global:
  - secure: "DJhGAxWd+XaMuUjro9Vzdg0vj1ZogPBLemlT8RzIAnaSCzuxnb0a3hZyZFWGhrJ9Dc2QVf/DLgm6QRQZp+QBfqn0mLAoy3lKOFw2jLgBFa5PPDRKJKPEXVtX6LjO675Z4F/Kts4DRiaLeUi8VdYyj22Ful7ewsHP8VUuW6dIsNytUC5Mhkyh2yBLFAKsk8L6bR5Qesx7VAbcLO/9BZ++4PFxeY0SuBMzbSLv3zMGlxmNy/0rfHAhO1/zNE/ZtYWGLWy6QK81GJp1xkBfGiy9xX8V89zsfEdJgJEAidDADxZTAuOBf11XthIMAALjp3gIA1nS4zc8bxrcepdUEirHmPdTG73DB8Kj2GweCGqowCQiTmgmjUtJAfiflW/ONLKtl7pCfAGPdE1DcMB02CmSoD6Rtpjmf9D80UWUsTw7hJ8nqzK8Dtnio7QvZ4j/TrPdAPAVp9j2kQGhsEoXorgVpdml7tm6sHX8o0/mTcflRsXjKGTFIc3liyt8SMvj43aviV2L6zJZFLKcH79T4SKvYz6AqlGNOKfZbq2qawcV1BL3N1VV8rkZ4/A3w9YjANrVPmsclRaHudgb8x8XligCBsqoGYI5JrZEU7qp1tYSG9pFnKpR4sboXkmqKXm3FZO24Jggt8kzg0H1R7lZb/wLy8BxGX5Zj7SeS4yTXRFlRJY="
  - PYPI_USER_NAME: "chaostoolkit"

script: 
  - bash ci.bash
